name: main

on:
  push:
    branches:
      - main
      
env:
  REGISTRY: antgoncharik
  IMAGE_NAME: notifier
  CONTAINER_NAME: notifier

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build container image and push
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 
          
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:  
      - name: Run services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            # docker run -d --restart=always -e FROM_MAIL=${{ secrets.FROM_MAIL }} -e PASSWORD_MAIL=${{ secrets.PASSWORD_MAIL }} -e HOST_MAIL=${{ secrets.HOST_MAIL }} -e TELOXIDE_TOKEN=${{ secrets.TELOXIDE_TOKEN }} -e BROKER_URI=${{ secrets.BROKER_URI }} --name ${{ env.CONTAINER_NAME }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker run -d --restart=always -e FROM_MAIL=${{ secrets.FROM_MAIL }} --name ${{ env.CONTAINER_NAME }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
